---
<% chef_versions = %w( 11 latest ) %>
<% platforms = %w( centos-6.6 ) %>
<% aem_versions = %w( 5.6.1 6.0.0 ) %>

driver:
  name: vagrant
  customize:
      memory: 3072
      cpus: 2

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
<% platforms.each do |p| %>
<%   chef_versions.each do |chef_version| %>
  - name: <%= p %>-chef-<%= chef_version %>
    driver_config:
      box: opscode-<%= p %>
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_<%= p %>_chef-provisionerless.box
      require_chef_omnibus: <%= chef_version %>
    attributes:
      cq:
        license:
          url: <%= ENV['CQ_LICENSE_URL'] %>
      java:
          '7':
            x86_64:
              url: <%= ENV['JAVA_JDK_7_X86_64_URL'] || "http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz" %>
              checksum: 'bad9a731639655118740bee119139c1ed019737ec802a630dd7ad7aab4309623'
<%   end %>
<% end %>

suites:
<% aem_versions.each do |v| %>
  <% env = "CQ_V#{v.delete('.')}_JAR_URL" %>
  - name: author-v<%= v %>
    run_list:
      - recipe[cq::author]
    attributes:
      cq:
        version: <%= v %>
        jar:
          url: <%= ENV[env] %>
  - name: publish-v<%= v %>
    run_list:
      - recipe[cq::publish]
    attributes:
      cq:
        version: <%= v %>
        jar:
          url: <%= ENV[env] %>
  - name: combined-v<%= v %>
    run_list:
      - recipe[cq::author]
      - recipe[cq::publish]
    attributes:
      cq:
        version: <%= v %>
        jar:
          url: <%= ENV[env] %>
  - name: author-run_mode-v<%= v %>
    run_list:
      - recipe[cq::author]
    attributes:
      cq:
        author:
          run_mode: 'crx2,author'
        version: <%= v %>
        jar:
          url: <%= ENV[env] %>

  - name: publish-run_mode-v<%= v %>
    run_list:
      - recipe[cq::publish]
    attributes:
      cq:
        publish:
          run_mode: 'crx2,publish'
        version: <%= v %>
        jar:
          url: <%= ENV[env] %>
  - name: osgi_configs-v<%= v %>
    run_list:
      - recipe[cq::author]
      - recipe[cq::_osgi_config_create_regular]
      - recipe[cq::_osgi_config_create_factory]
      - recipe[cq::_osgi_config_delete_regular]
      - recipe[cq::_osgi_config_delete_factory]
    attributes:
      cq:
        version: <%= v %>
        jar:
          url: <%= ENV[env] %>
<% end %>
