---
driver:
  name: vagrant
  customize:
      memory: 2048
      cpus: 2
  network:
      - ["forwarded_port", {guest: 4502, host: 4502}]
      - ["forwarded_port", {guest: 4503, host: 4503}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-6.5
    attributes:
      cq:
        license:
          url: <%= ENV['CQ_LICENSE_URL'] %>
      java:
        jdk:
          '7':
            x86_64:
              url: <%= ENV['JAVA_JDK_7_X86_64_URL'] || "http://download.oracle.com/otn-pub/java/jdk/7u72-b14/jdk-7u72-linux-x64.tar.gz" %>
          '6':
            x86_64:
              url: <%= ENV['JAVA_JDK_6_X86_64_URL'] || "http://download.oracle.com/otn-pub/java/jdk/6u45-b06/jdk-6u45-linux-x64.bin" %>

suites:
  - name: author-v5.6.1
    run_list:
      - recipe[cq::author]
    attributes:
      cq:
        jar:
          url: <%= ENV['CQ_V561_JAR_URL'] %>

  - name: publish-v5.6.1
    run_list:
      - recipe[cq::publish]
    attributes:
      cq:
        jar:
          url: <%= ENV['CQ_V561_JAR_URL'] %>
