AllCops:
    Exclude:
        - 'Vagrantfile'
        - 'metadata.rb'
        - 'Thorfile'
        - 'Berksfile'

Encoding:
    Enabled: false

LineLength:
    Max: 80

HashSyntax:
    EnforcedStyle: hash_rockets
