AllCops:
  Exclude:
    - 'Berksfile'
    - 'Gemfile'
    - 'metadata.rb'
    - 'Thorfile'
    - 'Vagrantfile'

Encoding:
  Enabled: false

LineLength:
  Max: 80

HashSyntax:
  EnforcedStyle: hash_rockets

Documentation:
  Enabled: false

ClassLength:
  Enabled: false

AbcSize:
  Max: 30
