AllCops:
    Exclude:
        - 'Vagrantfile'
        - 'metadata.rb'
        - 'Thorfile'
        - 'Berskfile'

Encoding:
    Enabled: false

LineLength:
    Max: 80

MethodLength:
    Max: 30

HashSyntax:
    EnforcedStyle: hash_rockets

CyclomaticComplexity:
    Max: 10

PerceivedComplexity:
    Max: 10
